### ISSUE TITLE
Token for `API` can't be just a string.

### ISSUE THREAD

**Issue by FeeeeK** [timoniq/telegrinder#1]
It's cool that using the `Token` class we can load tokens from environment variables, but if the environment variables are loaded elsewhere, then passing a simple string to the `API` constructor without `mypy` errors is impossible.

**Comment by timoniq** [comment]
> It's cool that using the `Token` class we can load tokens from environment variables, but if the environment variables are loaded elsewhere, then passing a simple string to the `API` constructor without `mypy` errors is impossible.

What's the problem with `Token("string")`? `Token` class is derived from `str`.

**Comment by FeeeeK** [comment]
It should be the other way around. There must be a `str` in the typehint, then both the `str` and the `Token` will be accepted.

**Comment by timoniq** [comment]
I know what type hints are for therefore I don't understand why passing `str` should be made desirable. `Token` wrapping makes this data type much more definite (which should have been desirable for you if you are using mypy), enables adding further checks and improves application logic.

**Comment by FeeeeK** [comment]
Now this type is not so useful for me, because I already get the token from env, but this causes an error.
![image](https://user-images.githubusercontent.com/26704473/182739870-053be2e1-79b1-4461-9ff8-29e7c39fed65.png)

**Comment by timoniq** [comment]
Please use `Token(TG_TOKEN)` if you want to correspond telegrinder policy logic.
My previous answer was exhaustive.
