### ISSUE TITLE
improve the way the Variative field is passed

### ISSUE THREAD

**Issue by timoniq** [timoniq/telegrinder#149]
rn if you need to pass some dataclass with a variative field u have to do it in a VERY ugly way

```python
await callback.edit_media(
    caption=text,
    media=InputMediaPhoto("photo", Variative[InputFile, str](url))
)
```

something must be done about this..

**Comment by luwqz1** [comment]
maybe it's worth making a transfer issue to fntypes?

**Comment by timoniq** [comment]
> maybe it's worth making a transfer issue to fntypes?

Still don't know if its going to be an fntypes-based type change or a bunch of regenerated type models for inputs. Hence the problem is represented via input model I'll keep it here
