### ISSUE TITLE
exception on msgspec decode is not caught

### ISSUE THREAD

**Issue by timoniq** [timoniq/telegrinder#155]
.../packages/telegrinder/msgspec_utils.py", line 292, in decode
    return msgspec.json.decode(
           ^^^^^^^^^^^^^^^^^^^^
msgspec.DecodeError: JSON is malformed: invalid character (byte 4)

Expected behaviour:
`decode_callback_data` must return Nothing value

**Comment by luwqz1** [comment]
@timoniq что бля
