### ISSUE TITLE
`IsPrivate` rule (and some other) do not support `CallbackQueryCute` even when the latter must be supported

### ISSUE THREAD

**Issue by prostomarkeloff** [timoniq/telegrinder#83]
### ⚪️ Checklist ⚪️
* [x]  ❕ I'm sure this is a **bug** in the **framework** ❕
* [x] 🟢 I have the **latest** version of the **framework** installed 🟢

### ✏️ Description ✏️
`IsPrivate` rule (and some other) do not support `CallbackQueryCute` even when the latter must be supported.

`IsPrivate` rule checks if `chat_type` is `private`. `Message` does support it and `IsPrivate` inherits from `MessageRule` that doesn't let anything but `Message` go there. There should be something like `CallbackQueryOrMessageRule`, adapter of which supports both `Message` and `CallbackQuery`

**Comment by timoniq** [comment]
CallbackQueryOrMessageRule -> probably SourceAdapter

also a node might created for compositional approach (`PrivateSource` / `PublicSource`)

**Comment by luwqz1** [comment]
i did this: https://github.com/timoniq/telegrinder/blob/dev/telegrinder/bot/rules/is_from.py#L28
