### ISSUE TITLE
`get_event_loop` calls is deprecated in python3.10

### ISSUE THREAD

**Issue by FeeeeK** [timoniq/telegrinder#9]
In python3.10 the `get_event_loop` function from asyncio is deprecated and should be replaced by `get_running_loop`, but it should only be called inside asynchronous functions, so I recommend removing all `.loop` attributes and using `get_running_loop` instead, or `new_event_loop` in case of `run_forever` function, because it makes no sense to cache the loop object - it can lead to a lot of problems in future and doesn't improve performance.

**Comment by timoniq** [comment]
ok
